name: CD with Gradle and Docker

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ☕️ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: 🐘 Build with Gradle
        run: ./gradlew clean build -x test --stacktrace

      - name: 💣 Build and Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/joyprotein:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/joyprotein:latest

      - name: 🚀 Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Stopping and removing existing container"
            sudo docker stop joyprotein || true
            sudo docker rm joyprotein || true
            
            echo "Pulling the latest image"
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/joyprotein:latest

            echo "Running container"
            sudo docker run -d --name joyprotein -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/joyprotein:latest

            echo "Cleaning up unused Docker images"
            sudo docker image prune -f